//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/MEGA144H7/connectors/MEGA144.yaml
#pragma once

Gpio GENERATED_OUTPUTS[] = {
	Gpio::A8, // PA8
	Gpio::A9, // PA9
	Gpio::A10, // PA10
	Gpio::A11, // PA11
	Gpio::A12, // PA12
	Gpio::A13, // PA13
	Gpio::A14, // PA14
	Gpio::A15, // PA15
	Gpio::B2, // PB2
	Gpio::B3, // PB3
	Gpio::B4, // PB4
	Gpio::B5, // PB5
	Gpio::B6, // PB6
	Gpio::B7, // PB7
	Gpio::B8, // PB8
	Gpio::B9, // PB9
	Gpio::B10, // PB10
	Gpio::B11, // PB11
	Gpio::B12, // PB12
	Gpio::B13, // PB13
	Gpio::B14, // PB14
	Gpio::B15, // PB15
	Gpio::C6, // PC6
	Gpio::C7, // PC7
	Gpio::C8, // PC8
	Gpio::C9, // PC9
	Gpio::C10, // PC10
	Gpio::C11, // PC11
	Gpio::C12, // PC12
	Gpio::C13, // PC13
	Gpio::C14, // PC14
	Gpio::C15, // PC15
	Gpio::D0, // PD0
	Gpio::D1, // PD1
	Gpio::D2, // PD2
	Gpio::D3, // PD3
	Gpio::D4, // PD4
	Gpio::D5, // PD5
	Gpio::D6, // PD6
	Gpio::D7, // PD7
	Gpio::D8, // PD8
	Gpio::D9, // PD9
	Gpio::D10, // PD10
	Gpio::D11, // PD11
	Gpio::D12, // PD12
	Gpio::D13, // PD13
	Gpio::D14, // PD14
	Gpio::D15, // PD15
	Gpio::E0, // PE0
	Gpio::E1, // PE1
	Gpio::E2, // PE2
	Gpio::E3, // PE3
	Gpio::E4, // PE4
	Gpio::E5, // PE5
	Gpio::E6, // PE6
	Gpio::E7, // PE7
	Gpio::E8, // PE8
	Gpio::E9, // PE9
	Gpio::E10, // PE10
	Gpio::E11, // PE11
	Gpio::E12, // PE12
	Gpio::E13, // PE13
	Gpio::E14, // PE14
	Gpio::E15, // PE15
	Gpio::F0, // PF0
	Gpio::F1, // PF1
	Gpio::F2, // PF2
	Gpio::F3, // PF3
	Gpio::F4, // PF4
	Gpio::F5, // PF5
	Gpio::F6, // PF6
	Gpio::F7, // PF7
	Gpio::F8, // PF8
	Gpio::F9, // PF9
	Gpio::F10, // PF10
	Gpio::F11, // PF11
	Gpio::F12, // PF12
	Gpio::F13, // PF13
	Gpio::F14, // PF14
	Gpio::F15, // PF15
	Gpio::G0, // PG0
	Gpio::G1, // PG1
	Gpio::G2, // PG2
	Gpio::G3, // PG3
	Gpio::G4, // PG4
	Gpio::G5, // PG5
	Gpio::G6, // PG6
	Gpio::G7, // PG7
	Gpio::G8, // PG8
	Gpio::G9, // PG9
	Gpio::G10, // PG10
	Gpio::G11, // PG11
	Gpio::G12, // PG12
	Gpio::G13, // PG13
	Gpio::G14, // PG14
	Gpio::G15, // PG15
	Gpio::H0, // PH0
	Gpio::H1, // PH1
	Gpio::H2, // PH2
	Gpio::H3, // PH3
	Gpio::H4, // PH4
	Gpio::H5, // PH5
	Gpio::H6, // PH6
	Gpio::H7, // PH7
	Gpio::H8, // PH8
	Gpio::H9, // PH9
	Gpio::H10, // PH10
	Gpio::H11, // PH11
	Gpio::H12, // PH12
	Gpio::H13, // PH13
	Gpio::H14, // PH14
	Gpio::H15, // PH15
	Gpio::I0, // PI0
	Gpio::I1, // PI1
	Gpio::I2, // PI2
	Gpio::I3, // PI3
	Gpio::I4, // PI4
	Gpio::I5, // PI5
	Gpio::I6, // PI6
	Gpio::I7, // PI7
	Gpio::I8, // PI8
	Gpio::I9, // PI9
	Gpio::I10, // PI10
	Gpio::I11, // PI11
	Gpio::I12, // PI12
	Gpio::I13, // PI13
	Gpio::I14, // PI14
	Gpio::I15, // PI15
	Gpio::J0, // PJ0
	Gpio::J1, // PJ1
	Gpio::J2, // PJ2
	Gpio::J3, // PJ3
	Gpio::J4, // PJ4
	Gpio::J5, // PJ5
	Gpio::J6, // PJ6
	Gpio::J7, // PJ7
	Gpio::J8, // PJ8
	Gpio::J9, // PJ9
	Gpio::J10, // PJ10
	Gpio::J11, // PJ11
	Gpio::J12, // PJ12
	Gpio::J13, // PJ13
	Gpio::J14, // PJ14
	Gpio::J15, // PJ15
	Gpio::K0, // PK0
	Gpio::K1, // PK1
	Gpio::K2, // PK2
	Gpio::K3, // PK3
	Gpio::K4, // PK4
	Gpio::K5, // PK5
	Gpio::K6, // PK6
	Gpio::K7, // PK7
	Gpio::K8, // PK8
	Gpio::K9, // PK9
	Gpio::K10, // PK10
	Gpio::K11, // PK11
	Gpio::K12, // PK12
	Gpio::K13, // PK13
	Gpio::K14, // PK14
	Gpio::K15, // PK15
// "PA8",
// "PA9",
// "PA10",
// "PA11",
// "PA12",
// "PA13",
// "PA14",
// "PA15",
// "PB2",
// "PB3",
// "PB4",
// "PB5",
// "PB6",
// "PB7",
// "PB8",
// "PB9",
// "PB10",
// "PB11",
// "PB12",
// "PB13",
// "PB14",
// "PB15",
// "PC6",
// "PC7",
// "PC8",
// "PC9",
// "PC10",
// "PC11",
// "PC12",
// "PC13",
// "PC14",
// "PC15",
// "PD0",
// "PD1",
// "PD2",
// "PD3",
// "PD4",
// "PD5",
// "PD6",
// "PD7",
// "PD8",
// "PD9",
// "PD10",
// "PD11",
// "PD12",
// "PD13",
// "PD14",
// "PD15",
// "PE0",
// "PE1",
// "PE2",
// "PE3",
// "PE4",
// "PE5",
// "PE6",
// "PE7",
// "PE8",
// "PE9",
// "PE10",
// "PE11",
// "PE12",
// "PE13",
// "PE14",
// "PE15",
// "PF0",
// "PF1",
// "PF2",
// "PF3",
// "PF4",
// "PF5",
// "PF6",
// "PF7",
// "PF8",
// "PF9",
// "PF10",
// "PF11",
// "PF12",
// "PF13",
// "PF14",
// "PF15",
// "PG0",
// "PG1",
// "PG2",
// "PG3",
// "PG4",
// "PG5",
// "PG6",
// "PG7",
// "PG8",
// "PG9",
// "PG10",
// "PG11",
// "PG12",
// "PG13",
// "PG14",
// "PG15",
// "PH0",
// "PH1",
// "PH2",
// "PH3",
// "PH4",
// "PH5",
// "PH6",
// "PH7",
// "PH8",
// "PH9",
// "PH10",
// "PH11",
// "PH12",
// "PH13",
// "PH14",
// "PH15",
// "PI0",
// "PI1",
// "PI2",
// "PI3",
// "PI4",
// "PI5",
// "PI6",
// "PI7",
// "PI8",
// "PI9",
// "PI10",
// "PI11",
// "PI12",
// "PI13",
// "PI14",
// "PI15",
// "PJ0",
// "PJ1",
// "PJ2",
// "PJ3",
// "PJ4",
// "PJ5",
// "PJ6",
// "PJ7",
// "PJ8",
// "PJ9",
// "PJ10",
// "PJ11",
// "PJ12",
// "PJ13",
// "PJ14",
// "PJ15",
// "PK0",
// "PK1",
// "PK2",
// "PK3",
// "PK4",
// "PK5",
// "PK6",
// "PK7",
// "PK8",
// "PK9",
// "PK10",
// "PK11",
// "PK12",
// "PK13",
// "PK14",
// "PK15",
};
