//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/MEGA144H7/connectors/MEGA144.yaml
#pragma once

#define PIN_54 M144_A0
#define PIN_55 M144_A1
#define PIN_56 M144_A2
#define PIN_57 M144_A3
#define PIN_58 M144_A4
#define PIN_59 M144_A5
#define PIN_60 M144_A6
#define PIN_61 M144_A7
#define PIN_62 M144_A8
#define PIN_63 M144_A9
#define PIN_64 M144_A10
#define PIN_65 M144_A11
#define PIN_66 M144_A12
#define PIN_67 M144_A13
#define PIN_68 M144_A14
#define PIN_69 M144_A15
