//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/M144H7BLACK/connectors/M144.yaml
#pragma once

Gpio GENERATED_OUTPUTS[] = {
	Gpio::M144_D0, // D0
	Gpio::M144_D1, // D1
	Gpio::M144_D2, // D2
	Gpio::M144_D3, // D3
	Gpio::M144_D4, // D4
	Gpio::M144_D5, // D5
	Gpio::M144_D6, // D6
	Gpio::M144_D7, // D7
	Gpio::M144_D8, // D8
	Gpio::M144_D9, // D9
	Gpio::M144_D10, // D10
	Gpio::M144_D11, // D11
	Gpio::M144_D12, // D12
	Gpio::M144_D13, // D13
	Gpio::M144_D14, // D14
	Gpio::M144_D15, // D15
	Gpio::M144_D16, // D16
	Gpio::M144_D17, // D17
	Gpio::M144_D18, // D18
	Gpio::M144_D19, // D19
	Gpio::M144_D20, // D20
	Gpio::M144_D21, // D21
	Gpio::M144_D22, // D22
	Gpio::M144_D23, // D23
	Gpio::M144_D24, // D24
	Gpio::M144_D25, // D25
	Gpio::M144_D26, // D26
	Gpio::M144_D27, // D27
	Gpio::M144_D28, // D28
	Gpio::M144_D29, // D29
	Gpio::M144_D30, // D30
	Gpio::M144_D31, // D31
	Gpio::M144_D32, // D32
	Gpio::M144_D33, // D33
	Gpio::M144_D34, // D34
	Gpio::M144_D35, // D35
	Gpio::M144_D36, // D36
	Gpio::M144_D37, // D37
	Gpio::M144_D38, // D38
	Gpio::M144_D39, // D39
	Gpio::M144_D40, // D40
	Gpio::M144_D41, // D41
	Gpio::M144_D42, // D42
	Gpio::M144_D43, // D43
	Gpio::M144_D44, // D44
	Gpio::M144_D45, // D45
	Gpio::M144_D46, // D46
	Gpio::M144_D47, // D47
	Gpio::M144_D48, // D48
	Gpio::M144_D49, // D49
	Gpio::M144_D50, // D50
	Gpio::M144_D51, // D51
	Gpio::M144_D52, // D52
	Gpio::M144_D53, // D53
	Gpio::A11, // PA11
	Gpio::A12, // PA12
	Gpio::A13, // PA13
	Gpio::A14, // PA14
	Gpio::B0, // PB0
	Gpio::B1, // PB1
	Gpio::C0, // PC0
	Gpio::C1, // PC1
	Gpio::C2, // PC2
	Gpio::C3, // PC3
	Gpio::C4, // PC4
	Gpio::C5, // PC5
	Gpio::C10, // PC10
	Gpio::C11, // PC11
	Gpio::C12, // PC12
	Gpio::C14, // PC14
	Gpio::C15, // PC15
	Gpio::D0, // PD0
	Gpio::D1, // PD1
	Gpio::D2, // PD2
	Gpio::F0, // PF0
	Gpio::F1, // PF1
	Gpio::F2, // PF2
	Gpio::F3, // PF3
	Gpio::F4, // PF4
	Gpio::F5, // PF5
	Gpio::F6, // PF6
	Gpio::F7, // PF7
	Gpio::F8, // PF8
	Gpio::F9, // PF9
	Gpio::F10, // PF10
	Gpio::F11, // PF11
	Gpio::F12, // PF12
	Gpio::F13, // PF13
	Gpio::F14, // PF14
	Gpio::F15, // PF15
	Gpio::G0, // PG0
	Gpio::G1, // PG1
	Gpio::G2, // PG2
	Gpio::G3, // PG3
	Gpio::G4, // PG4
	Gpio::G5, // PG5
	Gpio::G6, // PG6
	Gpio::G7, // PG7
	Gpio::G8, // PG8
	Gpio::G9, // PG9
	Gpio::G10, // PG10
	Gpio::G11, // PG11
	Gpio::G12, // PG12
	Gpio::G13, // PG13
	Gpio::H0, // PH0
	Gpio::H1, // PH1
	Gpio::H2, // PH2
	Gpio::H3, // PH3
	Gpio::H4, // PH4
	Gpio::H5, // PH5
	Gpio::H6, // PH6
	Gpio::H7, // PH7
	Gpio::H8, // PH8
	Gpio::H9, // PH9
	Gpio::H10, // PH10
	Gpio::H11, // PH11
	Gpio::H12, // PH12
	Gpio::H13, // PH13
	Gpio::H14, // PH14
	Gpio::H15, // PH15
	Gpio::I0, // PI0
	Gpio::I1, // PI1
	Gpio::I2, // PI2
	Gpio::I3, // PI3
	Gpio::I4, // PI4
	Gpio::I5, // PI5
	Gpio::I6, // PI6
	Gpio::I7, // PI7
	Gpio::I8, // PI8
	Gpio::I9, // PI9
	Gpio::I10, // PI10
	Gpio::I11, // PI11
	Gpio::I12, // PI12
	Gpio::I13, // PI13
	Gpio::I14, // PI14
	Gpio::I15, // PI15
	Gpio::J0, // PJ0
	Gpio::J1, // PJ1
	Gpio::J2, // PJ2
	Gpio::J3, // PJ3
	Gpio::J4, // PJ4
	Gpio::J5, // PJ5
	Gpio::J6, // PJ6
	Gpio::J7, // PJ7
	Gpio::J8, // PJ8
	Gpio::J9, // PJ9
	Gpio::J10, // PJ10
	Gpio::J11, // PJ11
	Gpio::J12, // PJ12
	Gpio::J13, // PJ13
	Gpio::J14, // PJ14
	Gpio::J15, // PJ15
	Gpio::K0, // PK0
	Gpio::K1, // PK1
	Gpio::K2, // PK2
	Gpio::K3, // PK3
	Gpio::K4, // PK4
	Gpio::K5, // PK5
	Gpio::K6, // PK6
	Gpio::K7, // PK7
	Gpio::K8, // PK8
	Gpio::K9, // PK9
	Gpio::K10, // PK10
	Gpio::K11, // PK11
	Gpio::K12, // PK12
	Gpio::K13, // PK13
	Gpio::K14, // PK14
	Gpio::K15, // PK15
	Gpio::MEGA_EPIC_1_PWM_T3_D3, // MEGA_EPIC_1_PWM_T3_D3
	Gpio::MEGA_EPIC_1_PWM_T3_D5, // MEGA_EPIC_1_PWM_T3_D5
	Gpio::MEGA_EPIC_1_PWM_T4_D6, // MEGA_EPIC_1_PWM_T4_D6
	Gpio::MEGA_EPIC_1_PWM_T4_D7, // MEGA_EPIC_1_PWM_T4_D7
	Gpio::MEGA_EPIC_1_PWM_T4_D8, // MEGA_EPIC_1_PWM_T4_D8
	Gpio::MEGA_EPIC_1_PWM_T1_D11, // MEGA_EPIC_1_PWM_T1_D11
	Gpio::MEGA_EPIC_1_PWM_T1_D12, // MEGA_EPIC_1_PWM_T1_D12
	Gpio::MEGA_EPIC_1_PWM_T5_D44, // MEGA_EPIC_1_PWM_T5_D44
	Gpio::MEGA_EPIC_1_PWM_T5_D45, // MEGA_EPIC_1_PWM_T5_D45
	Gpio::MEGA_EPIC_1_PWM_T5_D46, // MEGA_EPIC_1_PWM_T5_D46
	Gpio::MEGA_EPIC_1_SLOW_D39, // MEGA_EPIC_1_SLOW_D39
	Gpio::MEGA_EPIC_1_SLOW_D40, // MEGA_EPIC_1_SLOW_D40
	Gpio::MEGA_EPIC_1_SLOW_D41, // MEGA_EPIC_1_SLOW_D41
	Gpio::MEGA_EPIC_1_SLOW_D42, // MEGA_EPIC_1_SLOW_D42
	Gpio::MEGA_EPIC_1_SLOW_D43, // MEGA_EPIC_1_SLOW_D43
	Gpio::MEGA_EPIC_1_SLOW_D47, // MEGA_EPIC_1_SLOW_D47
	Gpio::MEGA_EPIC_1_SLOW_D48, // MEGA_EPIC_1_SLOW_D48
	Gpio::MEGA_EPIC_1_SLOW_D49, // MEGA_EPIC_1_SLOW_D49
	Gpio::CAN_PIN_0, // CAN_PIN_0
	Gpio::CAN_PIN_1, // CAN_PIN_1
	Gpio::CAN_PIN_2, // CAN_PIN_2
	Gpio::CAN_PIN_3, // CAN_PIN_3
	Gpio::CAN_PIN_4, // CAN_PIN_4
	Gpio::CAN_PIN_5, // CAN_PIN_5
	Gpio::CAN_PIN_6, // CAN_PIN_6
	Gpio::CAN_PIN_7, // CAN_PIN_7
	Gpio::VIRTUAL_OUTPUT_1, // VIRTUAL_OUTPUT_1
	Gpio::VIRTUAL_OUTPUT_2, // VIRTUAL_OUTPUT_2
	Gpio::VIRTUAL_OUTPUT_3, // VIRTUAL_OUTPUT_3
	Gpio::VIRTUAL_OUTPUT_4, // VIRTUAL_OUTPUT_4
	Gpio::VIRTUAL_OUTPUT_5, // VIRTUAL_OUTPUT_5
	Gpio::VIRTUAL_OUTPUT_6, // VIRTUAL_OUTPUT_6
	Gpio::VIRTUAL_OUTPUT_7, // VIRTUAL_OUTPUT_7
	Gpio::VIRTUAL_OUTPUT_8, // VIRTUAL_OUTPUT_8
	Gpio::VIRTUAL_OUTPUT_9, // VIRTUAL_OUTPUT_9
	Gpio::VIRTUAL_OUTPUT_10, // VIRTUAL_OUTPUT_10
	Gpio::VIRTUAL_OUTPUT_11, // VIRTUAL_OUTPUT_11
	Gpio::VIRTUAL_OUTPUT_12, // VIRTUAL_OUTPUT_12
	Gpio::VIRTUAL_OUTPUT_13, // VIRTUAL_OUTPUT_13
	Gpio::VIRTUAL_OUTPUT_14, // VIRTUAL_OUTPUT_14
	Gpio::VIRTUAL_OUTPUT_15, // VIRTUAL_OUTPUT_15
	Gpio::VIRTUAL_OUTPUT_16, // VIRTUAL_OUTPUT_16
// "D0",
// "D1",
// "D2",
// "D3",
// "D4",
// "D5",
// "D6",
// "D7",
// "D8",
// "D9",
// "D10",
// "D11",
// "D12",
// "D13",
// "D14",
// "D15",
// "D16",
// "D17",
// "D18",
// "D19",
// "D20",
// "D21",
// "D22",
// "D23",
// "D24",
// "D25",
// "D26",
// "D27",
// "D28",
// "D29",
// "D30",
// "D31",
// "D32",
// "D33",
// "D34",
// "D35",
// "D36",
// "D37",
// "D38",
// "D39",
// "D40",
// "D41",
// "D42",
// "D43",
// "D44",
// "D45",
// "D46",
// "D47",
// "D48",
// "D49",
// "D50",
// "D51",
// "D52",
// "D53",
// "PA11",
// "PA12",
// "PA13",
// "PA14",
// "PB0",
// "PB1",
// "PC0",
// "PC1",
// "PC2",
// "PC3",
// "PC4",
// "PC5",
// "PC10",
// "PC11",
// "PC12",
// "PC14",
// "PC15",
// "PD0",
// "PD1",
// "PD2",
// "PF0",
// "PF1",
// "PF2",
// "PF3",
// "PF4",
// "PF5",
// "PF6",
// "PF7",
// "PF8",
// "PF9",
// "PF10",
// "PF11",
// "PF12",
// "PF13",
// "PF14",
// "PF15",
// "PG0",
// "PG1",
// "PG2",
// "PG3",
// "PG4",
// "PG5",
// "PG6",
// "PG7",
// "PG8",
// "PG9",
// "PG10",
// "PG11",
// "PG12",
// "PG13",
// "PH0",
// "PH1",
// "PH2",
// "PH3",
// "PH4",
// "PH5",
// "PH6",
// "PH7",
// "PH8",
// "PH9",
// "PH10",
// "PH11",
// "PH12",
// "PH13",
// "PH14",
// "PH15",
// "PI0",
// "PI1",
// "PI2",
// "PI3",
// "PI4",
// "PI5",
// "PI6",
// "PI7",
// "PI8",
// "PI9",
// "PI10",
// "PI11",
// "PI12",
// "PI13",
// "PI14",
// "PI15",
// "PJ0",
// "PJ1",
// "PJ2",
// "PJ3",
// "PJ4",
// "PJ5",
// "PJ6",
// "PJ7",
// "PJ8",
// "PJ9",
// "PJ10",
// "PJ11",
// "PJ12",
// "PJ13",
// "PJ14",
// "PJ15",
// "PK0",
// "PK1",
// "PK2",
// "PK3",
// "PK4",
// "PK5",
// "PK6",
// "PK7",
// "PK8",
// "PK9",
// "PK10",
// "PK11",
// "PK12",
// "PK13",
// "PK14",
// "PK15",
// "MEGA_EPIC_1_PWM_T3_D3",
// "MEGA_EPIC_1_PWM_T3_D5",
// "MEGA_EPIC_1_PWM_T4_D6",
// "MEGA_EPIC_1_PWM_T4_D7",
// "MEGA_EPIC_1_PWM_T4_D8",
// "MEGA_EPIC_1_PWM_T1_D11",
// "MEGA_EPIC_1_PWM_T1_D12",
// "MEGA_EPIC_1_PWM_T5_D44",
// "MEGA_EPIC_1_PWM_T5_D45",
// "MEGA_EPIC_1_PWM_T5_D46",
// "MEGA_EPIC_1_SLOW_D39",
// "MEGA_EPIC_1_SLOW_D40",
// "MEGA_EPIC_1_SLOW_D41",
// "MEGA_EPIC_1_SLOW_D42",
// "MEGA_EPIC_1_SLOW_D43",
// "MEGA_EPIC_1_SLOW_D47",
// "MEGA_EPIC_1_SLOW_D48",
// "MEGA_EPIC_1_SLOW_D49",
// "CAN_PIN_0",
// "CAN_PIN_1",
// "CAN_PIN_2",
// "CAN_PIN_3",
// "CAN_PIN_4",
// "CAN_PIN_5",
// "CAN_PIN_6",
// "CAN_PIN_7",
// "VIRTUAL_OUTPUT_1",
// "VIRTUAL_OUTPUT_2",
// "VIRTUAL_OUTPUT_3",
// "VIRTUAL_OUTPUT_4",
// "VIRTUAL_OUTPUT_5",
// "VIRTUAL_OUTPUT_6",
// "VIRTUAL_OUTPUT_7",
// "VIRTUAL_OUTPUT_8",
// "VIRTUAL_OUTPUT_9",
// "VIRTUAL_OUTPUT_10",
// "VIRTUAL_OUTPUT_11",
// "VIRTUAL_OUTPUT_12",
// "VIRTUAL_OUTPUT_13",
// "VIRTUAL_OUTPUT_14",
// "VIRTUAL_OUTPUT_15",
// "VIRTUAL_OUTPUT_16",
};
